# Generated by Django 4.2 on 2023-05-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCurso', models.IntegerField(max_length=100)),
                ('codigoDisciplina', models.IntegerField(max_length=100)),
            ],
        ),
    ]
